# ✅ Part A: Fundamentals Answers
### 1. What is Data Analysis?

**Answer:**

Data Analysis is the process of collecting, cleaning, transforming, and interpreting data to find useful information, patterns, and insights.

It helps in:

- Making better decisions

- Understanding trends

- Solving real-world problems

👉 Example: Analyzing customer purchase data to understand buying behavior.

### 2. Steps to Plan a Data Science Project

**Answer:**

A Data Science Project follows these steps:

1. Problem Understanding

- Define the objective (e.g., predict customer churn)

2. Data Collection

- Gather data from sources like CSV, database, API

3. Data Cleaning

- Handle missing values, remove duplicates

4. Data Exploration (EDA)

- Understand patterns using charts and statistics

5. Feature Engineering

- Create new useful features from data

6. Model Building

- Apply ML algorithms (like Logistic Regression)

7. Model Evaluation

- Check accuracy, precision, recall

8. Deployment (Optional)

- Use model in real-world applications

### 3. Machine Learning Problem Statement

**Answer:**

**Problem:**
Predict whether a customer will churn or not based on their purchase behavior.

Input Features:

- Age

- Income

- Purchase history

- Frequency of buying

**Output:**

Churn (Yes / No)

Type of Problem:
👉 Classification Problem

### 4. What are Tensors? (Simple + In-depth)
**✅ Definition:**

Tensors are multi-dimensional arrays used to store data in machine learning.

| Type         | Example       | Description            |
| ------------ | ------------- | ---------------------- |
| Scalar (0D)  | 5             | Single value           |
| Vector (1D)  | [1, 2, 3]     | List of values         |
| Matrix (2D)  | [[1,2],[3,4]] | Table                  |
| Tensor (3D+) | [[[...]]]     | Multi-dimensional data |


In [1]:
import numpy as np

# Scalar (0D)
a = np.array(5)

# Vector (1D)
b = np.array([1, 2, 3])

# Matrix (2D)
c = np.array([[1, 2], [3, 4]])

# 3D Tensor
d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("Scalar:", a)
print("Vector:", b)
print("Matrix:\n", c)
print("Tensor:\n", d)

Scalar: 5
Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# ✅ Part B: Data Acquisition (Code)
#### 🔹 1. Load CSV File using Pandas

In [ ]:
import pandas as pd
import json
import sqlite3
import mysql.connector
import requests


# Load CSV file
df_csv = pd.read_csv("data.csv")

# Display first 5 rows
print(df_csv.head())

# Basic info
print(df_csv.info())

   customer_id     name  age  income  purchase_count churn
0            1    Alice   25   50000               5    No
1            2      Bob   30   60000               3   Yes
2            3  Charlie   35   70000               6    No
3            4    David   40   80000               2   Yes
4            5      Eva   28   65000               4    No
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   customer_id     5 non-null      int64 
 1   name            5 non-null      object
 2   age             5 non-null      int64 
 3   income          5 non-null      int64 
 4   purchase_count  5 non-null      int64 
 5   churn           5 non-null      object
dtypes: int64(4), object(2)
memory usage: 372.0+ bytes
None


#### 🔹 2. Parse JSON File

In [ ]:

# Load JSON file
with open("data.json") as file:
    data = json.load(file)

# Convert to DataFrame
df_json = pd.DataFrame(data)

print(df_json.head())

   customer_id     name  age  income  purchase_count churn
0            1    Alice   25   50000               5    No
1            2      Bob   30   60000               3   Yes
2            3  Charlie   35   70000               6    No
3            4    David   40   80000               2   Yes
4            5      Eva   28   65000               4    No


#### 🔹 3. Connect to SQL Database & Fetch Data

In [6]:

# Connect to database
conn = sqlite3.connect("database.db")

# Query data
query = "SELECT * FROM customers"

df_sql = pd.read_sql(query, conn)

print(df_sql.head())

# Close connection
conn.close()

   customer_id     name  age  income  purchase_count churn
0            1    Alice   25   50000               5    No
1            2      Bob   30   60000               3   Yes
2            3  Charlie   35   70000               6    No
3            4    David   40   80000               2   Yes
4            5      Eva   28   65000               4    No


#### 🔹 4. Fetch Data from API

In [ ]:

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

data = response.json()

df_api = pd.DataFrame(data)

print(df_api.head())

ProgrammingError: 1049 (42000): Unknown database 'dataprofiler'